### ISSUE TITLE
Suggestion: Make Colored Water act as water

### ISSUE THREAD

**Issue by 123FLO321** [Cozary/Issue-Tracker#71]
Currently it is not possible to for example place lily pads, kelp or coral under water.
Additionally water logging could be added by integrating with the "fluidlogged" mod.

**Comment by Cozary** [comment]
I don't know if the lily pads, kelp or coral thing is possible, because it may go hand in hand with the fact that it doesn't have the ability to water logging. Anyway, I'll see if I can do something.

The Fluidlogged mod only allows adding other fluids for the devs of the Fabric version. So I can't do anything, you should add them by hand.

**Comment by Cozary** [comment]
I can't do anything with a block being in water because that is "waterlog" and can't be done.

The lilypads worked until 1.19.4, no idea because after 1.20 they don't work.
