### ISSUE TITLE
Add ability to configure loot tables of trinkets

### ISSUE THREAD

**Issue by JaredRichardWilliam** [Cozary/Issue-Tracker#88]
I saw this mentioned at https://www.curseforge.com/minecraft/mc-mods/nameless-trinkets/comments#:~:text=March%2021%2C%202024-,6388998,-In%20reply%20to, but then I have not been able to find it mentioned elsewhere whether it will be added in the future.

**Comment by Cozary** [comment]
Yes, it will be re-added in the future, I just haven't gotten around to it yet.

I'm moving my mods to Multiloader and Nameless Trinkets is the last one and before I get to that I'll fix all the stuff that's been pending for a while. So you can expect that to be back "soon" since I'm on the last mod before I get to Nameless Trinkets.

**Comment by JaredRichardWilliam** [comment]
@Cozary, thanks!

**Comment by Cozary** [comment]
Done in code, will appear in the next update
